id: I4D163660
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T16:45:37+00:00'
last_modified: '2022-06-07T15:28:44.391414+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W19836
  title: པོ་ཏ་ལར་བཞུགས་པའི་དགེ་ལུགས་གསུང་འབུམ་གྱི་དཀར་ཆག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    E77B:
      image_group_id: I1PD96415
      title: ''
      total_pages: 993
      order: 1
      base_file: E77B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
