id: P002906
initial_creation_type: ocr
source_metadata:
  id: bdr:W19836
  title: པོ་ཏ་ལར་བཞུགས་པའི་དགེ་ལུགས་གསུང་འབུམ་གྱི་དཀར་ཆག
  author: ''
  volumes:
    f12f3ece73f442f894f8599267806f12:
      image_group_id: I1PD96415
      title: ''
      volume_number: 1
      total_pages: 993
