id: P002906
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 10:27:36.251921
source_metadata:
  id: bdr:W19836
  title: པོ་ཏ་ལར་བཞུགས་པའི་དགེ་ལུགས་གསུང་འབུམ་གྱི་དཀར་ཆག
  author: ''
  volumes:
    f12f3ece73f442f894f8599267806f12:
      image_group_id: I1PD96415
      title: ''
      volume_number: 1
      total_pages: 993
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
